### ISSUE TITLE
如何在chatgpt-nextweb使用？

### ISSUE THREAD

**Issue by hallfay0** [zhu327/gemini-openai-proxy#1]
已经用docker安装完成，使用 http://192.168.1.1:8080/v1等等地址， 加上geminipro api无法使用

**Comment by zhu327** [comment]
I tested it myself on the chatbox and it worked by directly inputting http://127.0.0.1:8080 along with the Google AI Studio API key. Please ensure that generativelanguage.googleapis.com is accessible.

**Comment by dhlsam** [comment]
部署后再lobe使用成功，但是问话gemnin api 调用的是PaLM-2模型

**Comment by zhu327** [comment]
> 部署后再lobe使用成功，但是问话gemnin api 调用的是PaLM-2模型

Gemini Pro就这德行，你可以到v2ex上看下，有人甚至问出来是文心一言

**Comment by hallfay0** [comment]
奇怪，我的就是不行
  "endpoint": "http://192.168.3.25:17777",
  "error": {
    "cause": {
      "name": "ConnectTimeoutError",
      "code": "UND_ERR_CONNECT_TIMEOUT",
      "message": "Connect Timeout Error"
    }
  }
}

**Comment by zhu327** [comment]
I have tested chatbox and OpenAI Translator, and also tried Pal Chat app on iOS, all of them work well. The project itself does not support the legacy OpenAI API, so any applications using the legacy OpenAI API would not be compatible.

**Comment by zhu327** [comment]
> 奇怪，我的就是不行 "endpoint": "http://192.168.3.25:17777", "error": { "cause": { "name": "ConnectTimeoutError", "code": "UND_ERR_CONNECT_TIMEOUT", "message": "Connect Timeout Error" } } }

Perhaps you need a VPN to access generativelanguage.googleapis.com.

**Comment by hallfay0** [comment]
> > 奇怪，我的根本不行 "endpoint": " http://192.168.3.25:17777", "error": { "cause": { "name": "ConnectTimeoutError", "code": "UND_ERR_CONNECT_TIMEOUT", "message ": "连接超时错误" } } }
> 
> 也许您需要 VPN 才能访问generativelanguage.googleapis.com。

我在洛杉矶，没墙。。。

**Comment by zhu327** [comment]
> > > 奇怪，我的根本不行 "endpoint": " http://192.168.3.25:17777", "error": { "cause": { "name": "ConnectTimeoutError", "code": "UND_ERR_CONNECT_TIMEOUT", "message ": "连接超时错误" } } }
> > 
> > 
> > 也许您需要 VPN 才能访问generativelanguage.googleapis.com。
> 
> 我在洛杉矶，没墙。。。

You can locally build a file, launch it, and see what the input content is.

**Comment by zhu327** [comment]
Alternatively, you can check the standard output content of the Docker container. I will reopen the issue.

**Comment by hallfay0** [comment]
I am encountering this issue because I am just beginning to learn LINUX, and I am not sure about the problem. I will continue to investigate and if I can resolve it on my own, I will let you know. The following is the Docker log.    
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /v1/models                --> github.com/zhu327/gemini-openai-proxy/api.ModelsHandler (4 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/zhu327/gemini-openai-proxy/api.ChatProxyHandler (4 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2023/12/17 - 13:47:15 | 404 |       1.103µs |   192.168.3.239 | GET      "/"

**Comment by zhu327** [comment]
@hallfay0 I tried adding the route for the homepage and handling CORS errors. You can give it another try.

**Comment by zhu327** [comment]
Confirm that ChatGPT NextWeb is compatible.
