### ISSUE TITLE
Vercel

### ISSUE THREAD

**Issue by nu-dev2024** [zhu327/gemini-openai-proxy#15]
Create for vercel script pliss

**Comment by zhu327** [comment]
Maximum timeout for vercel is 10s, but in my experience gemini pro would frequently exceed 10s, so that's not really a viable proposition

Recommended to deploy at fly.io, I'm also using fly.io and it's awesome

**Comment by zhu327** [comment]
https://github.com/zuisong/gemini-openai-proxy

Maybe this project is suitable for you
