### ISSUE TITLE
希望能兼容 function calling

### ISSUE THREAD

**Issue by fatwang2** [zhu327/gemini-openai-proxy#16]
Gemini 也支持 function calling，格式跟 OpenAI 类似，希望能做个兼容

**Comment by zhu327** [comment]
https://github.com/google/generative-ai-go/issues/32

Not available yet, SDK does not support

**Comment by fatwang2** [comment]
我看Gemini的官方文档，现在已经有测试版的function
calling功能了，已经有明确的接口文档了，我理解请求的时候请求beta的model就可以

**Comment by zhu327** [comment]
The gemini openai proxy uses the official GoLang SDK. Currently the SDK has not encapsulated the function call related functions yet. You can refer to the link in the previous reply

**Comment by zhu327** [comment]
The SDK now supports function calls, but it requires developers with specific needs to contribute pull requests.
