### ISSUE TITLE
Replied sometimes contain /n

### ISSUE THREAD

**Issue by yashsinha-aero** [zhu327/gemini-openai-proxy#18]
The gemini pro responses will randomly contain, /n sometimes instead of actually going to the next line. I suspect it’s similar to the previous issue of quotation marks getting printed.

**Comment by zhu327** [comment]
也许你可以debug一下, 在出现类似情况下, 打印出request/response data

**Comment by zhu327** [comment]
Perhaps you can debug it, in case of similar situations, print out the request/response data

**Comment by zhu327** [comment]
I think I've identified this issue. In Gemini, when streaming Markdown output, it occasionally gets interrupted. For example, in a reply like:

```
```Test stream text.\n this is look good for me.
```

You can see the Markdown tags starting with ``````, but for some unknown reason, the streaming output gets interrupted. As a result, the closing ``` tag for this text is missing, leading to the observed issue. If you encounter this problem, you can try regenerating it once. Currently, there is no other workaround.
