### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by bestpika** [zhu327/gemini-openai-proxy#21]
Hello, I found that any call returns error 400 without making any modifications to the program, and the message is 429.
But when I directly call the Gemini Pro API with the Gemini Pro data format, it works fine.
I originally thought it was an incorrect key, but intentionally changed the key to the wrong one, and got the message Error 400.

The following is the data for when I called.
```json
{
  "stream":false,
  "model":"gpt-3.5-turbo",
  "messages":[
  {
    "role":"user",
    "content":"HELLO"
  }]
}
```
```json
{
  "code": 400,
  "message": "genai send message error: googleapi: Error 429:",
  "type": ""
}
```

**Comment by bestpika** [comment]
I found that I am running into an overall usage limit. If I change the model to v1beta, I can bypass this limit. Is there a way to make this modification?

**Comment by zhu327** [comment]
try zhu327/gemini-openai-proxy:v1beta

**Comment by bestpika** [comment]
Hello, I'm not using Docker.
Is there a parameter that can switch to v1beta when compiling into an executable file?

**Comment by zhu327** [comment]
> Hello, I'm not using Docker. Is there a parameter that can switch to v1beta when compiling into an executable file?

It is suggested to copy the binary from the docker container
