### ISSUE TITLE
genai get stream message error proto: (line 2:3): unknown field "error"

### ISSUE THREAD

**Issue by bi1101** [zhu327/gemini-openai-proxy#22]
Hi, I sometimes get this error message recently. I presume it's due to Google changes?

`genai get stream message error proto: (line 2:3): unknown field "error"`

**Comment by zhu327** [comment]
I tried the new argument, but I found an issue with it, so I rolled back the code, you can re deploy the docker image to solve this issue

**Comment by zhu327** [comment]
One more thing, I found that the current code will also return this error, but this should be a Google issue

**Comment by zhu327** [comment]
I feel that the Google SDK is broken, so I'll roll the code again, the latest docker image can be parameterized

**Comment by bi1101** [comment]
Hi. After pulling the new Docker image and reverting to your previous code, it appears that this issue persists:
`genai get stream message error proto: (line 2:3): unknown field "error"`
