### ISSUE TITLE
Pythagora open ai API: 'choices' issue

### ISSUE THREAD

**Issue by sureshpatel66** [zhu327/gemini-openai-proxy#23]
Pythagora

Implementing task #1:  Set up a Node.js project with package.json, install all necessary dependencies, and set up an express server.

I have successfully using for GPT pilot. during code generation, There was a problem with request to openai API:
'choices'

kindly help in this reg.

**Comment by zhu327** [comment]
Sorry, I didn't understand your question. Could you put a specific call interface request post data and response data here, which can help to pinpoint what the problem is?
