### ISSUE TITLE
proxy error L curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by nullnuller** [zhu327/gemini-openai-proxy#26]
$ curl http://127.0.0.1:8081/v1/chat/completions  -H "Content-Type: application/json"  -H "Authorization: Bearer $API_KEY"  -d '{
     "model": "gpt-4",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
 }'
curl: (52) Empty reply from server

Here's the docker:
$ docker ps -a
CONTAINER ID   IMAGE                               COMMAND         CREATED         STATUS         PORTS                    NAMES
9a49c5c0b3e4   zhu327/gemini-openai-proxy:latest   "/app/gemini"   3 minutes ago   Up 3 minutes   0.0.0.0:8081->8081/tcp   gemini

**Comment by zhu327** [comment]
curl 'https://generativelanguage.googleapis.com/v1beta/models?key=<YOUR_API_KEY>'

Please confirm that you have access to gemini-1.0-ultra-latest or gemini-1.5-pro-latest

**Comment by nullnuller** [comment]
models/gemini-1.0-pro
models/gemini-1.0-pro-001
models/gemini-1.0-pro-latest
models/gemini-1.0-pro-vision-latest
models/gemini-pro
models/gemini-pro-vision

Which OAI model is supported?

**Comment by zhu327** [comment]
Model Mapping:

gpt-3.5-turbo -> gemini-1.0-pro-latest
gpt-4 -> gemini-1.0-ultra-latest
gpt-4-turbo-preview -> gemini-1.5-pro-latest
gpt-4-vision-preview -> gemini-1.0-pro-vision-latest

**Comment by nullnuller** [comment]
How can I modify it so that 

gpt-3.5-turbo -> gemini-1.0-pro
gpt-4 -> gemini-1.0-pro-latest
gpt-4-turbo-preview -> gemini-1.0-pro-latest
gpt-4-vision-preview -> gemini-pro-vision

**Comment by nullnuller** [comment]
> How can I modify it so that
> 
> gpt-3.5-turbo -> gemini-1.0-pro gpt-4 -> gemini-1.0-pro-latest gpt-4-turbo-preview -> gemini-1.0-pro-latest gpt-4-vision-preview -> gemini-pro-vision

Anyone?

**Comment by zhu327** [comment]
You should modify the code by yourself

**Comment by nullnuller** [comment]
> You should modify the code by yourself

Can you point to the code where it can be changed?
