### ISSUE TITLE
Chinese Location

### ISSUE THREAD

**Issue by 1487879421888** [zhu327/gemini-openai-proxy#29]
Hello,

I am reaching out on behalf of several users from the China region who have deployed the gemini-openai-proxy Docker image but are facing consistent access timeout issues. The error being encountered frequently is a connection reset during API interactions.

Given that there might be unique considerations for accessing services like these from China, could you provide guidance or recommendations on how to ensure reliable access? Are there specific configurations, additional proxy setups, or any other steps that we should consider to address this timeout problem?

Any help or suggestions you could offer would be greatly appreciated.

Thank you for your assistance.

Best regards,
Jack

**Comment by zhu327** [comment]
It is recommended to deploy the service in a region supported by gemini

https://ai.google.dev/gemini-api/docs/available-regions

**Comment by wisonyun** [comment]
can't support proxy?
