### ISSUE TITLE
感谢，可以支持gemini。但貌似不兼容openai模型

### ISSUE THREAD

**Issue by popdo** [zhu327/gemini-openai-proxy#3]
使用gemini没问题。但传入openai的模型和KEY时出错了

```js
{
    "error": "googleapi: Error 400:"
}
```

只能单向支持gemini吗

**Comment by zhu327** [comment]
I don't understand what you mean by using the OpenAI key. This project supports Gemini Pro and simply proxies Google's protocol to OpenAI's protocol.

The meaning of a 400 error is that there is a problem with the input parameters. Could you please provide the data you are sending when making the API request?

**Comment by popdo** [comment]
I’m very sorry, I didn’t express myself clearly enough. I would like to know if this agent also supports the original requests from OpenAI?

**Comment by zhu327** [comment]
> I’m very sorry, I didn’t express myself clearly enough. I would like to know if this agent also supports the original requests from OpenAI?

You do not need to use this proxy to use the Openai API. This proxy was not created for the purpose of crossover gfw.
