### ISSUE TITLE
The return value is not as expected

### ISSUE THREAD

**Issue by GodD6366** [zhu327/gemini-openai-proxy#30]
1. When making a call using curl, I receive an empty object as the return value.
<img width="743" alt="image" src="https://github.com/zhu327/gemini-openai-proxy/assets/17250383/e5670811-0a9f-473f-8032-95c3127ae027">

2. Using the “openai” npm package results in the same issue as with the curl call.
[npm package openai](https://www.npmjs.com/package/openai)

3. However, using other clients (such as OpenCat / ChatX) allows for successful proxying.
<img width="478" alt="image" src="https://github.com/zhu327/gemini-openai-proxy/assets/17250383/7636a659-3aea-428d-8d96-077edac4d647">

<img width="733" alt="image" src="https://github.com/zhu327/gemini-openai-proxy/assets/17250383/ce4124aa-06b1-4192-af11-f0d26d480a84">

**Comment by zhu327** [comment]
From your description, I can't see what the problem is. You can consider whether there is an interruption in the network. The intermediate node may block and tamper with data

**Comment by GodD6366** [comment]
> ata

If no other intermediate nodes modify the data, the direct curl call will get an empty object "{}", but you can use other clients to talk normally.

<img width="742" alt="image" src="https://github.com/zhu327/gemini-openai-proxy/assets/17250383/43edf12d-91de-4834-bb20-85c6a3ecdfde">

**Comment by zhu327** [comment]
As you can see in the README.md file I wrote an example with curl, I didn't face your issue

**Comment by GodD6366** [comment]
> As you can see in the README.md file I wrote an example with curl, I didn't face your issue

Okay, I’ve also checked the Docker logs and haven’t found any errors. I’m not sure how to proceed with the investigation either.
