### ISSUE TITLE
Feature request: Checking for Rate limiting blocking (error 429) and throttling back requests.

### ISSUE THREAD

**Issue by DIGist** [zhu327/gemini-openai-proxy#31]
Hi!

Love the tool! 

I hit a rate limit and received error 429 when working with a project..

Could you implement request throttling or request backoff delay to help alleviate the problem?

Feature request: Checking for Rate limiting blocking (error 429) and throttling back requests.

**Comment by zhu327** [comment]
I won't implement this feature. This tool only does forwarding. If you have a demand, you can fork and implement it yourself
