### ISSUE TITLE
Have the plan support Gemini 1.5 Flash？

### ISSUE THREAD

**Issue by jarlin8** [zhu327/gemini-openai-proxy#33]
Have the plan support Gemini 1.5 Flash？

**Comment by zhu327** [comment]
| GPT Model | Gemini Model |
|---|---|
| gpt-3.5-turbo | gemini-1.0-pro-latest |
| gpt-4 | gemini-1.5-flash-latest |
| gpt-4-turbo-preview | gemini-1.5-pro-latest |
| gpt-4-vision-preview | gemini-1.0-pro-vision-latest |

New Model Mapping
