### ISSUE TITLE
[Feature Request] Option to disable model mapping

### ISSUE THREAD

**Issue by charlie-moomoo** [zhu327/gemini-openai-proxy#35]
Currently, this project maps GPT models to Gemini models, which can cause model ID overlap on some projects such as [Open WebUI](https://openwebui.com/). It would be great if we have an option in which we can disable model mappings.

**Comment by ekatiyar** [comment]
Have the exact same usecase as you - ended up creating a fork of the project without the mappings [here](https://github.com/ekatiyar/gemini-openai-proxy/)

**Comment by zhu327** [comment]
@ekatiyar Thanks for your PR.
