### ISSUE TITLE
[Bug] Does not support single str for vision or multiple texts input for non-vision

### ISSUE THREAD

**Issue by ZihaoZhou** [zhu327/gemini-openai-proxy#40]
First thank @zhu327 and @ekatiyar for your great works.

I am using [this fork of repository](https://github.com/ekatiyar/gemini-openai-proxy) and notice that 

```
curl http://localhost:8080/v1/chat/completions \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer $GOOGLE_API_KEY" \
 -d '{
     "model": "gemini-1.5-vision-latest",
     "messages": [{"role": "user", "content": "Say this is a test."}],
     "temperature": 0.7
 }'
 ```

 ```
 {"code":400,"message":"message.multiContent: json.Unmarshal: json: cannot unmarshal string into Go value of type []openai.ChatMessagePart","type":""}
```

does not work, because the proxy forces the vision input to have multiple parts. But in practice, both openai and gemini vision models can accept input without images. I also notice that

```
curl http://localhost:8080/v1/chat/completions \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer $GOOGLE_API_KEY" \
 -d '{
     "model": "gemini-1.0-pro-latest",
     "messages": [{"role": "user", "content": [
        {"type": "text", "text": "Paraphrase this sentence."},
        {"type": "text", "text": "Say this is a test."}
     ]}],
     "temperature": 0.7
 }'
```

does not work, because the proxy forces the text input to have single part. But in practice, both openai and gemini models accept multiple text parts. 

Since gemini-1.0-pro-vision was already deprecated last month, I don't see why we cannot simply aggregate toStringGenaiContent() and toVisionGenaiContent() to handle all forms of input. I implemented it in my [fork](https://github.com/ZihaoZhou/gemini-openai-proxy/) and it solves both bugs. It also avoid the extra environment variable to toggle between gemini flash and pro vision.

**Comment by ekatiyar** [comment]
Nice fix! I don't use the vision model so didn't run into this issue. 

My main branch has a bunch of extra stuff, so if you'd be able to rebase your change onto this repo it should be pretty easy to just open up a PR here. One thing to note is that I've modified my model mapping changes in #41, but briefly looking over your changes it shouldn't be too big of an issue

**Comment by traderpedroso** [comment]
> First thank @zhu327 and @ekatiyar for your great works.
> 
> I am using [this fork of repository](https://github.com/ekatiyar/gemini-openai-proxy) and notice that
> 
> ```
> curl http://localhost:8080/v1/chat/completions \
>  -H "Content-Type: application/json" \
>  -H "Authorization: Bearer $GOOGLE_API_KEY" \
>  -d '{
>      "model": "gemini-1.5-vision-latest",
>      "messages": [{"role": "user", "content": "Say this is a test."}],
>      "temperature": 0.7
>  }'
> ```
> 
> ```
> {"code":400,"message":"message.multiContent: json.Unmarshal: json: cannot unmarshal string into Go value of type []openai.ChatMessagePart","type":""}
> ```
> 
> does not work, because the proxy forces the vision input to have multiple parts. But in practice, both openai and gemini vision models can accept input without images. I also notice that
> 
> ```
> curl http://localhost:8080/v1/chat/completions \
>  -H "Content-Type: application/json" \
>  -H "Authorization: Bearer $GOOGLE_API_KEY" \
>  -d '{
>      "model": "gemini-1.0-pro-latest",
>      "messages": [{"role": "user", "content": [
>         {"type": "text", "text": "Paraphrase this sentence."},
>         {"type": "text", "text": "Say this is a test."}
>      ]}],
>      "temperature": 0.7
>  }'
> ```
> 
> does not work, because the proxy forces the text input to have single part. But in practice, both openai and gemini models accept multiple text parts.
> 
> Since gemini-1.0-pro-vision was already deprecated last month, I don't see why we cannot simply aggregate toStringGenaiContent() and toVisionGenaiContent() to handle all forms of input. I implemented it in my [fork](https://github.com/ZihaoZhou/gemini-openai-proxy/) and it solves both bugs. It also avoid the extra environment variable to toggle between gemini flash and pro vision.

First, I'd like to thank @ekatiyar and @zhu327 for developing both the proxy by zhu327 and the embedding by ekatiyar. Now @ZihaoZhou's solution is perfect and very close to OpenAI! Congratulations ZihaoZhou, I believe now it only needs the functions to work in order to integrate with LangChain. Thank you all for the excellent work, I believe ZihaoZhou's solution deserves a pull request.

**Comment by zhu327** [comment]
Thanks for your PR.
