### ISSUE TITLE
Why did you use AI studio API and not direct REST API?

### ISSUE THREAD

**Issue by rakotomandimby** [zhu327/gemini-openai-proxy#42]
Hello,
Is there a technical reason why you use AI Studio API and not [the REST API](https://github.com/google/generative-ai-docs/blob/main/site/en/gemini-api/docs/get-started/rest.ipynb)?

```bash
curl https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$GOOGLE_API_KEY \
    -H 'Content-Type: application/json' \
    -X POST \
    -d '{
      "contents": [{
        "parts":[{
          "text": "Write a story about a magic backpack."}]}]}' 2> /dev/null
```

**Comment by zhu327** [comment]
This project uses the official Google generative-ai-go SDK from github.com/google/generative-ai-go.
