### ISSUE TITLE
Does this project support accessing the Gemini API through a proxy server?

### ISSUE THREAD

**Issue by gaozh424** [zhu327/gemini-openai-proxy#6]
Hi,
Thank you for your contribution and sharing, it's really great.
Does this project support accessing the Gemini API through a proxy server? 
I am unable to access Google from my region.

**Comment by zhu327** [comment]
I suggest deploying your project in a country where Gemini Pro API is accessible, or adding generativelanguage.googleapis.com to the proxy whitelist in your router, such as in OpenWrt.

This project utilizes the Google Genai SDK, and this feature cannot be implemented until the SDK supports proxy configuration.

**Comment by zhu327** [comment]
https://github.com/google/generative-ai-go/issues/17

**Comment by gaozh424** [comment]
> [google/generative-ai-go#17](https://github.com/google/generative-ai-go/issues/17)

Thank you very much for your reply. I will try to modify the code in handler.go and recompile to see if it works, or could you add an additional parameter?

**Comment by zhu327** [comment]
> > [google/generative-ai-go#17](https://github.com/google/generative-ai-go/issues/17)
> 
> Thank you very much for your reply. I will try to modify the code in handler.go and recompile to see if it works, or could you add an additional parameter?

Proxy support will not be considered until the issue with Google SDK is confirmed as closed.

**Comment by zhu327** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/#running-a-docker-daemon-behind-an-https_proxy

You can refer to here to configure proxy in docker container
