### ISSUE TITLE
pro vision cannot use text

### ISSUE THREAD

**Issue by kokojacket** [zhu327/gemini-openai-proxy#8]
I just found out that the update supports vision, but after using it, I found that using vision with plain text is not supported and must be accompanied by pictures.
![image](https://github.com/zhu327/gemini-openai-proxy/assets/74887370/9de5e04a-7973-4a6b-acfe-1ff8521f95ab)

**Comment by zhu327** [comment]
https://platform.openai.com/docs/guides/vision

I implemented the protocol according to the above documents. I am not sure if the original gpt-4-vision-preview supports plain text directly

**Comment by kokojacket** [comment]
Well, thanks
