### ISSUE TITLE
Can parameters be added to set gemini security threshold to BLOCK_NONE?

### ISSUE THREAD

**Issue by CatCars** [zhu327/gemini-openai-proxy#9]
gemini default review is too strict, totally unnecessary. Even the text of the quarrel between the protagonists in the movie subtitles is blocked.
Often report errors when doing translation work.
https://ai.google.dev/docs/safety_setting_gemini#safety-filters

**Comment by CatCars** [comment]
"threshold": "BLOCK_NONE"

**Comment by zhu327** [comment]
Done

**Comment by CatCars** [comment]
> 已完成 做

Thank you very much
